### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by klauspost** [bjwbell/gensimd#1]
It seems like the installation instructions should be updated.

* [ ] Add `go get github.com/bjwbell/gensimd`
* [ ] Remove https://
* [ ] `go install https://github.com/bjwbell/gensimd/simd/sse` is wrong path

**Comment by bjwbell** [comment]
Sorry about that, I never tested the install directions. I'll have it fixed shortly

**Comment by klauspost** [comment]
No problem. Just wanted to put it in, so I didn't forget it.

**Comment by bjwbell** [comment]
Hopefully the new instructions are correct.
