### ISSUE TITLE
x86 Instruction definitions

### ISSUE THREAD

**Issue by klauspost** [bjwbell/gensimd#2]
I am just dumping my thoughts.

* You have noted that immediates aren't supported.
* For SSE4+, you need to be able to supply additional registers, for instance [BLENDVPS](https://godoc.org/github.com/klauspost/intrinsics/x86/sse4#BlendvPs) takes a third parameter that must be in XMM0.
* Destination can be a GPR, for instance [PCMPISTRI](https://godoc.org/github.com/klauspost/intrinsics/x86/sse4#Cmpistri) writes the result to ECX.
* AVX has very nice 3 register versions of all SSE+ functions, which should of course also be possible.
* Composite instructions should somehow be possible. A simple example is [SetzeroSi128](https://godoc.org/github.com/klauspost/intrinsics/x86/sse2#SetzeroSi128), which is shorthand for `PXOR xmm, xmm`. [Set1Epi8](https://godoc.org/github.com/klauspost/intrinsics/x86/sse2#Set1Epi8) is similar example.

So `instructions.go` should at least have some way of indicating source/destination registers, as well as spilled registers.

Just to get an idea of how things would look, I changed my intrinsic generator to output in a format compatible with yours, and ran it through all x86 instrinsics.

It generates:

* `simd/xxx/xxx.go`, that should match `simd/sse2/sse2.go`, including documentation for each intrinsic.
* `codegen/xxx.go`, matching some of the stuff in "codegen/sse2.go"
* `codegen/xxx/instructions.go`, matching some of the stuff in "codegen/sse2/instructions.go"

All intrinsics that receive a pointer is skipped for the moment.

See the generated SSE2 here: https://gist.github.com/klauspost/c9a21edcf044087ee7a1
Download all sse/avx/misc files here: https://files.klauspost.com/simd.zip

**Comment by klauspost** [comment]
Added the generator as a separate [branch](https://github.com/klauspost/intrinsics/tree/gensimd).

**Comment by bjwbell** [comment]
I've been revamping the support for immediates. They work for `ShuffleI32x4/ShuffleU32x4`, I've updated the README.md, it's under the Gotchas section. Immediate support for SSE2 etc should be very easy to add. 

I'm not actually that happy with the instructions.go tables, like you said for SSE4+ additional registers need to be supplied. I haven't thought on how to restructure the tables yet. I'll think about it today. And hopefully come up with something reasonable. 

As part of register assignment and spilling I've added another instruction table (mostly copied from the go compiler) @ https://github.com/bjwbell/gensimd/blob/master/codegen/namesamd64.go#L772

So that'll also need to be modified.

I'll take a look at your generated intrinsics too.

Thanks!

**Comment by bjwbell** [comment]
*happy with the instructions.go tables => I meant to say the tables in gensimd/codegen/instramd64.go

**Comment by bjwbell** [comment]
FYI for immediates the code to load them is https://github.com/bjwbell/gensimd/blob/master/codegen/identifier.go#L195 (loadConst)

It only supports integers and floats right now. I don't think other types are needed but support could be added.

**Comment by bjwbell** [comment]
I pushed [Redesign intrinsic support](https://github.com/bjwbell/gensimd/commit/e02f8d345503b228ab7a5f5cfbf48a567fec80aa).

To add new intrinsics the *only* table that needs to be modified is `sse2instructions` in https://github.com/bjwbell/gensimd/blob/master/codegen/sse2.go

Immediates are supported (untested) and pointer arguments are supported (untested).

**Comment by bjwbell** [comment]
Destination GPR registers should work. Even if the destination register is implicit, [Support for implicit output operands](https://github.com/bjwbell/gensimd/commit/5174d81827c57232a74041d2e0a23394c2c19a70).

**Comment by bjwbell** [comment]
Closing, I think the instruction tables now satisfy all the requested features, except perhaps composite instructions.
