### ISSUE TITLE
vendored stringer can't read go1.7 or go1.8 packages

### ISSUE THREAD

**Issue by glycerine** [bjwbell/gensimd#5]
This seems like a very interesting library!  I tried to build it and ran into this:

osx 10.11.6 with go1.7.4 or go1.8beta2, the vendored version ofgolang.org/x/tools/cmd/stringer is out of date. It can't read the current package format:

~~~
jaten@jatens-MacBook-Pro ~/go/src/github.com/bjwbell/gensimd (master) $ go generate
stringer: checking package: codegen/codegen.go:4:2: could not import errors (reading expor\
t data: /usr/local/go/pkg/darwin_amd64/errors.a: import error /usr/local/go/pkg/darwin_amd\
64/errors.a:1:10 (byte offset = 9): expected keyword package, got "version")
gensimd.go:3: running "stringer": exit status 1

jaten@jatens-MacBook-Pro ~/go/src/github.com/bjwbell/gensimd (master) $ 
~~~
If I overwrite the vendored `stringer` with 2bbdb4568e161d12394da43e88b384c6be63928b from `Wed Aug 17 10:41:00 2016 -0700`, then go generate works without complaint.

Q: are there changes in the vendored libs, or should it work with the latest versions?

**Comment by bjwbell** [comment]
Thanks, I'll update this evening. If you have any requests feel free to
open an issue or email.

JW Bell

On Dec 19, 2016 11:40 PM, "Jason E. Aten, Ph.D." <notifications@github.com>
wrote:

This seems like a very interesting library! I tried to build it and ran
into this:

osx 10.11.6 with go1.7.4 or go1.8beta2, the vendored version
ofgolang.org/x/tools/cmd/stringer is out of date. It can't read the current
package format:

stringer: checking package: codegen/codegen.go:4:2: could not import
errors (reading expor\
t data: /usr/local/go/pkg/darwin_amd64/errors.a: import error
/usr/local/go/pkg/darwin_amd\
64/errors.a:1:10 (byte offset = 9): expected keyword package, got "version")
gensimd.go:3: running "stringer": exit status 1
jaten@jatens-MacBook-Pro ~/go/src/github.com/bjwbell/gensimd (master) $ ```

If I overwrite the vendored `stringer` with
2bbdb4568e161d12394da43e88b384c6be63928b from `Wed Aug 17 10:41:00
2016 -0700`, then go generate works without complaint.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bjwbell/gensimd/issues/5>, or mute the thread

**Comment by bjwbell** [comment]
A: No changes to stringer, but because stringer is in the same repo as the x/tools/ssa it came along for the ride. There is a change in the ssa package, the lifting of simd regs - https://github.com/bjwbell/tools/commit/8c0f3ace351d208a3840f410d2f3219bc3bd875a. 

The vendored version in https://github.com/bjwbell/tools/tree/gensimd should be updated now.

**Comment by bjwbell** [comment]
Removing all the vendor packages except ssa fixed the issue..
